In [33]:
import numpy as np
# np.random.seed(42)

In [34]:
np.random.randint(0,9,10)

array([7, 6, 7, 0, 6, 7, 6, 7, 4, 7])

In [45]:
data = np.zeros([10000, 10])

In [46]:
for i in range(data.shape[0]):
    data[i,:] = np.random.randint(0,10,10)

In [47]:
data[:50]

array([[4., 0., 5., 7., 6., 9., 7., 1., 0., 9.],
       [7., 3., 8., 6., 4., 7., 3., 8., 6., 3.],
       [3., 8., 9., 8., 7., 2., 5., 5., 5., 3.],
       [8., 4., 6., 3., 3., 0., 1., 2., 8., 9.],
       [2., 9., 3., 2., 3., 3., 9., 5., 6., 0.],
       [9., 9., 8., 3., 8., 4., 4., 2., 5., 8.],
       [9., 3., 0., 9., 2., 4., 8., 4., 6., 0.],
       [1., 8., 1., 5., 6., 7., 1., 9., 6., 1.],
       [4., 8., 7., 3., 2., 3., 5., 5., 8., 5.],
       [9., 3., 9., 9., 4., 0., 7., 7., 6., 7.],
       [2., 5., 0., 0., 6., 7., 1., 1., 7., 4.],
       [9., 5., 1., 2., 3., 6., 9., 1., 2., 1.],
       [4., 4., 4., 4., 5., 6., 6., 2., 4., 5.],
       [8., 1., 4., 4., 4., 0., 0., 3., 7., 6.],
       [8., 6., 7., 3., 8., 5., 1., 7., 5., 0.],
       [1., 0., 0., 0., 2., 2., 5., 0., 1., 0.],
       [8., 9., 8., 8., 7., 6., 1., 0., 2., 5.],
       [8., 6., 5., 0., 8., 9., 2., 5., 0., 9.],
       [0., 7., 0., 9., 8., 2., 0., 0., 2., 5.],
       [5., 4., 5., 9., 2., 2., 3., 2., 0., 9.],
       [9., 7., 8., 

In [48]:
data.shape

(10000, 10)

In [50]:
label = np.zeros([data.shape[0], 4])

In [51]:
label.shape

(10000, 4)

In [74]:
for i in range(len(label)):
    pointer = np.random.randint(0,9)
    
    if pointer > data.shape[1]-5:
        point = data[i, pointer:]
    else:
        label[i,:] = data[i, pointer:pointer+4]

In [90]:
data[:10]

array([[4., 0., 5., 7., 6., 9., 7., 1., 0., 9.],
       [7., 3., 8., 6., 4., 7., 3., 8., 6., 3.],
       [3., 8., 9., 8., 7., 2., 5., 5., 5., 3.],
       [8., 4., 6., 3., 3., 0., 1., 2., 8., 9.],
       [2., 9., 3., 2., 3., 3., 9., 5., 6., 0.],
       [9., 9., 8., 3., 8., 4., 4., 2., 5., 8.],
       [9., 3., 0., 9., 2., 4., 8., 4., 6., 0.],
       [1., 8., 1., 5., 6., 7., 1., 9., 6., 1.],
       [4., 8., 7., 3., 2., 3., 5., 5., 8., 5.],
       [9., 3., 9., 9., 4., 0., 7., 7., 6., 7.]])

In [91]:
label

array([[7., 6., 9., 7.],
       [8., 6., 4., 7.],
       [8., 9., 8., 7.],
       ...,
       [6., 4., 0., 4.],
       [0., 6., 0., 0.],
       [7., 8., 7., 8.]])

In [77]:
from keras.models import Model
from keras.layers import Input, LSTM, Dense

Using TensorFlow backend.


In [89]:
encoder_inputs = Input(shape=(None, data.shape[1]))
encoder = LSTM(10)
encoder_outputs= encoder(encoder_inputs)


encoder_states = [state_h, state_c]

In [82]:
# decoder_inputs = Input(shape=(label.shape[1]),)
decoder_lstm = LSTM(10, return_sequences=True, return_state=True)
decoder_outputs, _, _ = decoder_lstm(encoder_state)

decoder_dense = Dense(label.shape[1], activation='softmax')
decoder_outputs = decoder_dense(decoder_outputs)

NameError: name 'encoder_state' is not defined

In [80]:
model = Model([encoder_inputs, decoder_inputs], decoder_outputs)

In [ ]:
model.compile(optimizer='adams',
             loss='categorical_crossentropy')
model.fit([])