In [1]:
import numpy as np
# np.random.seed(42)

In [2]:
np.random.randint(0,9,10)

array([3, 2, 0, 2, 5, 7, 2, 8, 1, 8])

In [3]:
data = np.zeros([10000, 10])

In [4]:
for i in range(data.shape[0]):
    data[i,:] = np.random.randint(0,10,10)

In [5]:
data[:50]

array([[2., 9., 7., 5., 0., 7., 0., 5., 4., 0.],
       [0., 3., 0., 5., 4., 9., 9., 1., 7., 2.],
       [0., 7., 6., 3., 1., 9., 4., 4., 7., 3.],
       [5., 9., 5., 6., 8., 3., 7., 6., 1., 3.],
       [4., 6., 1., 5., 9., 2., 2., 2., 0., 2.],
       [8., 6., 0., 3., 6., 7., 7., 3., 8., 2.],
       [0., 2., 9., 4., 1., 6., 8., 6., 0., 5.],
       [5., 9., 1., 4., 5., 1., 5., 3., 4., 1.],
       [7., 4., 8., 6., 4., 3., 6., 6., 0., 1.],
       [6., 5., 7., 4., 0., 4., 0., 9., 7., 4.],
       [2., 6., 0., 1., 5., 1., 6., 6., 0., 5.],
       [5., 5., 4., 8., 6., 1., 1., 6., 9., 2.],
       [1., 4., 6., 5., 8., 7., 4., 6., 2., 6.],
       [8., 4., 7., 9., 7., 1., 6., 1., 2., 1.],
       [5., 2., 2., 7., 7., 3., 9., 1., 7., 1.],
       [9., 0., 1., 9., 1., 2., 2., 2., 2., 5.],
       [9., 5., 2., 7., 0., 0., 8., 4., 6., 9.],
       [1., 2., 7., 1., 4., 1., 4., 6., 6., 1.],
       [7., 2., 3., 5., 3., 9., 9., 7., 2., 2.],
       [7., 3., 8., 7., 5., 3., 3., 9., 7., 0.],
       [8., 9., 3., 

In [6]:
data.shape

(10000, 10)

In [7]:
label = np.zeros([data.shape[0], 4])

In [8]:
label.shape

(10000, 4)

In [9]:
for i in range(len(label)):
    pointer = np.random.randint(0,9)
    
    if pointer > data.shape[1]-5:
        point = data[i, pointer:]
    else:
        label[i,:] = data[i, pointer:pointer+4]

In [10]:
data[:10]

array([[2., 9., 7., 5., 0., 7., 0., 5., 4., 0.],
       [0., 3., 0., 5., 4., 9., 9., 1., 7., 2.],
       [0., 7., 6., 3., 1., 9., 4., 4., 7., 3.],
       [5., 9., 5., 6., 8., 3., 7., 6., 1., 3.],
       [4., 6., 1., 5., 9., 2., 2., 2., 0., 2.],
       [8., 6., 0., 3., 6., 7., 7., 3., 8., 2.],
       [0., 2., 9., 4., 1., 6., 8., 6., 0., 5.],
       [5., 9., 1., 4., 5., 1., 5., 3., 4., 1.],
       [7., 4., 8., 6., 4., 3., 6., 6., 0., 1.],
       [6., 5., 7., 4., 0., 4., 0., 9., 7., 4.]])

In [11]:
label

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 7., 6., 3.],
       ...,
       [0., 0., 0., 0.],
       [7., 1., 0., 9.],
       [8., 4., 8., 2.]])

In [12]:
from keras.models import Model
from keras.layers import Input, LSTM, Dense

Using TensorFlow backend.


In [13]:
encoder_inputs = Input(shape=(None, data.shape[1]))
encoder = LSTM(10)
encoder_outputs= encoder(encoder_inputs)


encoder_states = [state_h, state_c]

NameError: name 'state_h' is not defined

In [ ]:
# decoder_inputs = Input(shape=(label.shape[1]),)
decoder_lstm = LSTM(10, return_sequences=True, return_state=True)
decoder_outputs, _, _ = decoder_lstm(encoder_state)

decoder_dense = Dense(label.shape[1], activation='softmax')
decoder_outputs = decoder_dense(decoder_outputs)

In [ ]:
model = Model([encoder_inputs, decoder_inputs], decoder_outputs)

In [ ]:
model.compile(optimizer='adams',
             loss='categorical_crossentropy')
model.fit([])