In [1]:
from keras.models import Model
from keras.layers import Input
from keras.layers import LSTM
from numpy import array
# define model
inputs1 = Input(shape=(3, 1))
lstm1, state_h, state_c = LSTM(1, return_state=True)(inputs1)
model = Model(inputs=inputs1, outputs=[lstm1, state_h, state_c])
# define input data
data = array([0.1, 0.2, 0.3]).reshape((1,3,1))
# make and show prediction
print(model.predict(data))

Using TensorFlow backend.


[array([[-0.13050131]], dtype=float32), array([[-0.13050131]], dtype=float32), array([[-0.24236806]], dtype=float32)]


In [2]:
data

array([[[0.1],
        [0.2],
        [0.3]]])

In [8]:
from keras.models import Model
from keras.layers import Input
from keras.layers import LSTM
from numpy import array

# define model
inputs1 = Input(shape=(3, 1))
lstm1, state_h, state_c = LSTM(1, return_sequences=True, return_state=True)(inputs1)
model = Model(inputs=inputs1, outputs=[lstm1, state_h, state_c])

# define input data
data = array([0.1, 0.2, 0.3]).reshape((1,3,1))

# make and show prediction
preds = model.predict(data)

In [9]:
len(preds)

3

In [10]:
preds

[array([[[0.01656462],
         [0.04952363],
         [0.09805422]]], dtype=float32),
 array([[0.09805422]], dtype=float32),
 array([[0.19710572]], dtype=float32)]

### Cell state -> Cell memory dependent on $h_t$