In [2]:
import numpy as np
import tensorflow as tf

### Generate synthetic data

In [3]:
data = np.zeros([10000, 10])
for i in range(data.shape[0]):
    data[i,:] = np.random.randint(0,10,10)

In [4]:
data[:10]

array([[1., 3., 5., 4., 8., 9., 2., 9., 8., 2.],
       [0., 2., 0., 0., 0., 5., 3., 0., 8., 1.],
       [5., 6., 7., 4., 8., 3., 5., 6., 8., 5.],
       [1., 1., 2., 7., 0., 8., 6., 6., 4., 9.],
       [0., 2., 8., 0., 1., 7., 6., 2., 0., 3.],
       [1., 9., 5., 0., 0., 7., 0., 9., 4., 2.],
       [8., 7., 1., 1., 1., 2., 3., 4., 6., 3.],
       [7., 2., 6., 8., 1., 3., 8., 7., 8., 7.],
       [0., 2., 2., 6., 2., 8., 2., 8., 6., 9.],
       [9., 2., 9., 4., 3., 2., 2., 6., 6., 9.]])

In [5]:
label = np.zeros([data.shape[0], 4])
for i in range(len(label)):
    pointer = np.random.randint(0,9)
    
    if pointer > data.shape[1]-5:
        # get the last sequence of the data
        point = data[i, pointer:]
    else:
        label[i,:] = data[i, pointer:pointer+4]

In [6]:
data.shape[1]

10

In [19]:
label

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [3., 5., 6., 8.],
       ...,
       [0., 0., 0., 0.],
       [6., 0., 7., 6.],
       [6., 3., 2., 6.]])

### Model

In [14]:
N_OUTPUTS = label.shape[1]
N_INPUTS = data.shape[1]
N_HIDDEN_UNITS = 10 # Define here
N_EPOCHS = 100 # define here
# N_FEATURES = 1000]

In [9]:
inputs = tf.placeholder(tf.float32, shape=[None, N_INPUTS], name='input')
outputs = tf.placeholder(tf.float32, shape=[None, N_OUTPUTS], name='output') 

In [10]:
W = {
    'hidden': tf.Variable(tf.random_normal([N_INPUTS, N_HIDDEN_UNITS])),
    'output': tf.Variable(tf.random_normal([N_HIDDEN_UNITS, N_OUTPUTS]))
}
biases = {
    'hidden': tf.Variable(tf.random_normal([N_HIDDEN_UNITS], mean=1.0)),
    'output': tf.Variable(tf.random_normal([N_OUTPUTS], mean=1.0))
}

In [24]:
hidden = tf.matmul(inputs, W['hidden']) + biases['hidden']  # hidden layer
hidden = tf.nn.relu(hidden)
output_ = tf.matmul(hidden, W['output']) + biases['output']  # outputs
# split_layer = tf.split(output_,num_or_size_splits=N_OUTPUTS,axis=1)
preds = tf.nn.sigmoid(output_)

loss = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(logits=output_,
                                                             labels=outputs))
optimizer = tf.train.AdamOptimizer(0.001).minimize(loss)

correct_preds = tf.equal(tf.cast(tf.greater(preds, tf.constant(0.5)), tf.float32), 
                         outputs)

accuracy = tf.reduce_mean(tf.cast(correct_preds, tf.float32))
                                  
with tf.Session() as session:
    session.run(tf.global_variables_initializer())
    for epoch in range(N_EPOCHS):
        _, loss_per_epochs = session.run([optimizer, loss],feed_dict={inputs:data, outputs:label}) #should feed inputs and outputs as [Ax,Ay,Az]
        print('Epoch', epoch, 'out of', N_EPOCHS, 'loss:', loss_per_epochs)
    
    accuracy_test = session.run(accuracy, 
                             feed_dict={inputs:data, outputs:label})
    
    print('Accuracy {0}'.format(accuracy_test))
    
    preds = session.run(preds, feed_dict={inputs:data})
    
    print(preds)

Epoch 0 out of 100 loss: -0.2997018
Epoch 1 out of 100 loss: -0.55549276
Epoch 2 out of 100 loss: -0.81034744
Epoch 3 out of 100 loss: -1.0643262
Epoch 4 out of 100 loss: -1.3174007
Epoch 5 out of 100 loss: -1.5695033
Epoch 6 out of 100 loss: -1.8206918
Epoch 7 out of 100 loss: -2.070941
Epoch 8 out of 100 loss: -2.3201792
Epoch 9 out of 100 loss: -2.5684605
Epoch 10 out of 100 loss: -2.8158617
Epoch 11 out of 100 loss: -3.0623515
Epoch 12 out of 100 loss: -3.3079016
Epoch 13 out of 100 loss: -3.552503
Epoch 14 out of 100 loss: -3.7961652
Epoch 15 out of 100 loss: -4.038896
Epoch 16 out of 100 loss: -4.280904
Epoch 17 out of 100 loss: -4.5220513
Epoch 18 out of 100 loss: -4.7622867
Epoch 19 out of 100 loss: -5.001736
Epoch 20 out of 100 loss: -5.240451
Epoch 21 out of 100 loss: -5.4784093
Epoch 22 out of 100 loss: -5.715571
Epoch 23 out of 100 loss: -5.951968
Epoch 24 out of 100 loss: -6.1877384
Epoch 25 out of 100 loss: -6.42295
Epoch 26 out of 100 loss: -6.6576123
Epoch 27 out of 100

In [23]:
preds

array([[1.0000000e+00, 1.0000000e+00, 0.0000000e+00, 8.5393603e-33],
       [9.9999964e-01, 1.0000000e+00, 1.1256049e-07, 1.0000000e+00],
       [1.0000000e+00, 1.0000000e+00, 3.4758610e-37, 3.0898945e-35],
       ...,
       [1.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.9616179e-25],
       [1.0000000e+00, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 1.0000000e+00, 3.5030451e-28, 2.0764496e-15]],
      dtype=float32)

### Shared Model

In [ ]:
def to_sequence_model(data):
    hidden_1_layer = {'weights': tf.Variable(tf.random_normal([data.shape[1], n_nodes_hl1])),
                     'biases': tf.Variable(tf.random_normal([n_nodes_hl1]))}
    
    output_layer = { 'weights': tf.Variable(tf.random_normal([n_nodes_hl1, n_sigmoid_output])),
                    'biases': tf.Variable(tf.random_normal([n_sigmoid_output]))}
    
    l1 = tf.add(tf.matmul(data, hidden_1_layer['weights']), hidden_1_layer['biases'])
    l1 = tf.nn.relu(l1)
    
    logits_output = tf.add(tf.matmul(l1, output_layer['weights']), output_layer['biases'])
    